version: "3.9"
services:
  app:
    container_name: crypto-wallet-api
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      X_POSTGRESQL_HOST: "postgres"
      X_POSTGRESQL_PORT: "5432"
      X_POSTGRESQL_USER: "root"
      X_POSTGRESQL_DB_NAME: "database"
      X_POSTGRESQL_DB_SCHEMA: "crypto"
      X_POSTGRESQL_PASSWORD: "pass"
      X_REDIS_HOST: "redis"
      X_REDIS_PORT: "6379"
      X_REDIS_PASS: "pass"
    ports:
      - "8080:8080"
    volumes:
      - ./:/app
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./volumes/redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli","ping" ]
      interval: 2s
      timeout: 20s
      retries: 10
  postgres:
    container_name: database
    image: postgres:latest
    environment:
      POSTGRES_DB: "database"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "pass"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./seed:/seed
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 5s
      timeout: 5s
      retries: 5